version: '2'
services:
  web:
    image: wenzowski/dialogue-map-development
    restart: never
    mem_limit: 2048m
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      CIRCLECI: ${CIRCLECI}
      CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}
      CIRCLE_SHA1: ${CIRCLE_SHA1}
      CIRCLE_BRANCH: ${CIRCLE_BRANCH}
      CI_PULL_REQUEST: ${CI_PULL_REQUEST}
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./build:/app/build
      - ./node_modules:/app/node_modules
      - ./.git:/app/.git
  backside:
    restart: never
    volumes:
      - /var/local/dialogue-map-development/backside:/app/data/backside
  rethinkdb:
    restart: never
    volumes:
      - /var/local/dialogue-map-development:/data
  elasticsearch:
    restart: never
    volumes:
      - /var/local/dialogue-map-development:/usr/share/elasticsearch/data
